name: teleport
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #SIZER
  sizer: ^2.0.15
  #FLUTTER SVG
  flutter_svg: ^1.0.3
  #Clippers
  flutter_custom_clippers: ^2.0.0
  #PERCENT INDICATOR
  percent_indicator: ^4.0.0
  #DATETIEM PICKER
  flutter_datetime_picker: ^1.5.1
  #INTL
  intl: ^0.17.0
  # DOTTED BORDER
  dotted_border: ^2.0.0+2
  #ROLLER LIST
  roller_list: ^1.0.2
  # IMAGE STACK
  image_stack: ^2.1.1
  #TIMELINE TILE
  timeline_tile: ^2.0.0
  #DOTTED LINE
  dotted_line: ^3.1.0
  #CHANGE APP PACKAGE NAME
  change_app_package_name: ^1.0.0
  #RATING BAR
  flutter_rating_bar: ^4.0.0
  #TABLE CALENDAR
  table_calendar: ^3.0.5
  #CAROUSEL SLIDER
  carousel_slider: ^4.0.0
  #PINPUT
  pinput: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true


  assets:
     - assets/images/
     - assets/images/icon/
     - assets/images/temImage/


  fonts:
     - family: Gordita
       fonts:
          - asset: assets/fonts/Gordita Medium.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     - family: Gilroy
       fonts:
          - asset: assets/fonts/Gilroy-Bold.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
